
# python function that takes a pdf provided by a user alongside a description of what the pdf is, 
# and sends it first to an amazon s3 bucket archive but then also parses it into text and caches it 
# in an extra third attribute that will be generated by a different function. I expect this cache 
# to take the form of a Postgres database, but if you have a suggestion that is more appropriate for 
# long to short text chunks I'd like to hear it

import uuid
import os
import boto3
from dotenv import load_dotenv
import tempfile
import asyncio
from supabase import create_client
from pypdf import PdfReader
from fastapi import APIRouter, Form, File, UploadFile, BackgroundTasks, HTTPException
from starlette.concurrency import run_in_threadpool
from typing import List

import data_handlers

load_dotenv()
s3 = boto3.client("s3")
router = APIRouter()


def archive_pdf(pdf_path: str, document_id: str, document_name: str, description: str, special_types: list[str], bucket: str) -> tuple[str, str]:
    """
    Upload the original PDF to S3.

    Returns:
        (bucket, key)
    """

    key = f"documents/{document_id}/original.pdf"

    s3.upload_file(
        pdf_path,
        bucket,
        key,
        ExtraArgs={
            "ContentType": "application/pdf"
        }
    )

    return bucket, key

def parse_pdf_to_chunks(pdf_path: str, document_name: str, document_desc: str, special_types: list[str], db_connection, bucket, bucket_key):
    """
    Parse a PDF and store its text chunks in PostgreSQL.
    """

    reader = PdfReader(pdf_path) # object that can read pdfs

    chunk_index = 0

    for page_number, page in enumerate(reader.pages, start=1):
        # this currently chunks by page which is not the best strategy long term

        text = page.extract_text()

        if not text:
            continue

        # Placeholder chunking strategy for now.
        # This can later be replaced by a proper chunker.
        chunks = [text]

        for chunk in chunks:
            data_handlers.add_chunk(db_connection, document_name, document_desc, page_number, chunk_index, bucket_key, chunk)
            find_relevances(db_connection, text, document_desc, document_name, chunk_index, special_types)
            chunk_index == 1

def find_relevances(client, text, text_description, document_name, chunk_no, special_types):
    relevances = []
    if "utility_bill" in special_types:
        relevances.append("scope2_from_utility_bills")
        response = data_handlers.add_relevancy_to_chunk(client, document_name, chunk_no, task_name="scope2_from_utility_bills")
    # etc etc


async def async_main_orchestrator(pdf_path, document_name, description, special_types):

    document_id = str(uuid.uuid4()) # may be different to the supabase uuid

    # create bucket
    s3session = boto3.Session(region_name = 'eu-west-2')
    s3client = s3session.client("s3")
    bucket_name = document_name + document_id
    s3client.create_bucket(Bucket=bucket_name)
    bucket_response = s3client.list_buckets()
    bucket = bucket_response['Buckets'][-1]

    bucket, bucket_key = archive_pdf(pdf_path, document_id, document_name, description, special_types, bucket)

    # connect to database get db_connection
    sb_url = os.getenv("SUPABASE_URL")
    sb_key = os.getenv("SUPABASE_ADMIN_KEY")

    db_connection = create_client(
        sb_url,
        sb_key
    )

    parse_pdf_to_chunks(pdf_path, document_name, description, special_types, db_connection, bucket, bucket_key)

def main_orchestrator(pdf_path, document_name, description, special_types):

    document_id = str(uuid.uuid4()) # may be different to the supabase uuid

    # create bucket
    s3session = boto3.Session(region_name = 'eu-west-2')
    s3client = s3session.client("s3")
    bucket_name = document_name + document_id
    s3client.create_bucket(Bucket=bucket_name)
    bucket_response = s3client.list_buckets()
    bucket = bucket_response['Buckets'][-1]

    bucket, bucket_key = archive_pdf(pdf_path, document_id, document_name, description, special_types, bucket)

    # connect to database get db_connection
    sb_url = os.getenv("SUPABASE_URL")
    sb_key = os.getenv("SUPABASE_ADMIN_KEY")

    db_connection = create_client(
        sb_url,
        sb_key
    )

    parse_pdf_to_chunks(pdf_path, document_name, description, special_types, db_connection, bucket, bucket_key)



@router.post("/documents")
async def upload_document(
    background_tasks: BackgroundTasks,
    document_name: str = Form(...),
    description: str = Form(...), 
    file: UploadFile = File(...),
    special_types: List[str] = Form([])
    ):

    # FastAPI application functions

    cache_path = os.getenv("CACHE_PATH")
    
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False, dir=cache_path) as tmp:
            
        file_path = tmp.name

        contents = await file.read()
        tmp.write(contents)

    # await run_in_threadpool(main_orchestrator(file_path, document_name, description, special_types))
    # await async_main_orchestrator(file_path, document_name, description, special_types)

    print({"status": "success", "document_name": document_name, "file_path": file_path})

    #background_tasks.add_task(os.remove, file_path)

    return {"status": "success", "document_name": document_name, "file_path": file_path}



# test 3 bucket process
# test caching process
# candidate row cache + auditing interface
# switch the description from open text to a dropdown menu
# response handling (get claude to do this)
# archive system needs a revamp, need to figure out how to restrict access to only a company's own documents
# should restructure the forntend to be secure, filepath should not come from client side, instead