
# python function that takes a pdf provided by a user alongside a description of what the pdf is, 
# and sends it first to an amazon s3 bucket archive but then also parses it into text and caches it 
# in an extra third attribute that will be generated by a different function. I expect this cache 
# to take the form of a Postgres database, but if you have a suggestion that is more appropriate for 
# long to short text chunks I'd like to hear it

import uuid
import os
import boto3
from dotenv import load_dotenv
import tempfile
import asyncio
from pypdf import PdfReader
from fastapi import FastAPI, Form, File, UploadFile, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from starlette.concurrency import run_in_threadpool

load_dotenv()
s3 = boto3.client("s3")


def archive_pdf(pdf_path: str, document_id: str, description: str, bucket: str) -> tuple[str, str]:
    """
    Upload the original PDF to S3.

    Returns:
        (bucket, key)
    """

    key = f"documents/{document_id}/original.pdf"

    s3.upload_file(
        pdf_path,
        bucket,
        key,
        ExtraArgs={
            "ContentType": "application/pdf"
        }
    )

    return bucket, key

def parse_pdf_to_chunks(pdf_path: str, document_id: str, db_connection):
    """
    Parse a PDF and store its text chunks in PostgreSQL.
    """

    reader = PdfReader(pdf_path) # object that can read pdfs

    with db_connection.cursor() as cursor: #
        # switch to supabase?

        chunk_index = 0

        for page_number, page in enumerate(reader.pages, start=1):
            # this currently chunks by page which is not the best strategy long term

            text = page.extract_text()

            if not text:
                continue

            # Placeholder chunking strategy for now.
            # This can later be replaced by a proper chunker.
            chunks = [text]

            for chunk in chunks:

                cursor.execute(
                    """
                    INSERT INTO document_chunks (
                        id,
                        document_id,
                        chunk_index,
                        page_start,
                        page_end,
                        text
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        str(uuid.uuid4()),
                        document_id,
                        chunk_index,
                        page_number,
                        page_number,
                        chunk,
                    )
                )

                chunk_index += 1

        cursor.execute(
            """
            UPDATE documents
            SET processing_status = 'parsed',
                parsed_at = NOW()
            WHERE id = %s
            """,
            (document_id,)
        )

    db_connection.commit()

def find_relevances(text, text_description):
    relevances = []
    if text_description == "utility_bill":
        relevances.append("scope2_via_utility_bills")
    # etc etc

async def async_main_orchestrator(pdf_path, document_name, description):

    document_id = str(uuid.uuid4()) # may be different to the supabase uuid

    # create bucket
    s3session = boto3.Session(region_name = 'eu-west-2')
    s3client = s3session.client("s3")
    bucket_name = document_name + document_id
    s3client.create_bucket(Bucket=bucket_name)
    bucket_response = s3client.list_buckets()
    bucket = bucket_response['Buckets'][-1]

    bucket, key = archive_pdf(pdf_path, document_id, description, bucket)

    # connect to database get db_connection
    # set up supabase and use that instead

    parse_pdf_to_chunks(pdf_path, key, db_connection) # replace cursor with supabase if using that whihc might be better for now

def main_orchestrator(pdf_path, document_name, description):

    document_id = str(uuid.uuid4()) # may be different to the supabase uuid

    # create bucket
    s3session = boto3.Session(region_name = 'eu-west-2')
    s3client = s3session.client("s3")
    bucket_name = document_name + document_id
    s3client.create_bucket(Bucket=bucket_name)
    bucket_response = s3client.list_buckets()
    bucket = bucket_response['Buckets'][-1]

    bucket, key = archive_pdf(pdf_path, document_id, description, bucket)

    # connect to database get db_connection
    # set up supabase and use that instead

    parse_pdf_to_chunks(pdf_path, key, db_connection) # replace cursor with supabase if using that whihc might be better for now


# FastAPI application functions

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten this to your actual frontend origin in production
    allow_methods=["*"],
    allow_headers=["*"],
)

cache_path = os.getenv("CACHE_PATH")

@app.post("/documents")
async def upload_document(
    background_tasks: BackgroundTasks,
    document_name: str = Form(...), # these are clearly undefined
    description: str = Form(...), 
    file: UploadFile = File(...)
    ):
    
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False, dir=cache_path) as tmp:
            
        file_path = tmp.name

        contents = await file.read()
        tmp.write(contents)

    # await run_in_threadpool(main_orchestrator(file_path, document_name, description))
    # await async_main_orchestrator(file_path, document_name, description)

    print({"status": "success", "document_name": document_name, "file_path": file_path})

    #background_tasks.add_task(os.remove, file_path)

    return {"status": "success", "document_name": document_name, "file_path": file_path}




# das videos x 2
# flaw with form - says upload failed but prints the thing, also does not create a file

# Supabase Implementation
# test 3 bucket process

# LLM stuff

# candidate row cache + auditing interface


# Pick modules and Stuff

# Worldbuilding + Happy place building for apprentices
# Trees and Beetles
# Iris and the Minotaur Good Tone + Vibes, Morals don't fit
# Four Cooking Pots fine tune
# Mammoth story - goated fr