
import uuid
import os
import boto3
from dotenv import load_dotenv
import tempfile
import asyncio
from supabase import create_client
from pypdf import PdfReader
from fastapi import APIRouter, Form, File, UploadFile, BackgroundTasks, HTTPException, Depends
from starlette.concurrency import run_in_threadpool
from typing import List
import re

import data_handlers
import user_verifier


load_dotenv()
s3 = boto3.client("s3")
router = APIRouter()


# python function that takes a pdf provided by a user alongside a description of what the pdf is, 
# and sends it first to an amazon s3 bucket archive but then also parses it into text and caches it 
# in an extra third attribute that will be generated by a different function. Currently this cache 
# takes the form of a supabase database

# also acts as the backend for upload_form.html, processing its push requests
# parsed text is conencted to metadata and added to the raw_chunks table
# chunks are filtered and associated with tasks they seem useful for. This is currently done 
# algorithmically based on the special types the user provides


def archive_pdf(pdf_path: str, document_id: str, document_name: str, description: str, special_types: list[str], bucket: str) -> tuple[str, str]:
    """
    Upload the original PDF to S3.

    Returns:
        (bucket, key)
    """
    # create bucket
    s3session = boto3.Session(
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name=os.getenv("AWS_DEFAULT_REGION", "eu-west-2")
    )

    s3client = s3session.client("s3")

    safe_document_name = re.sub(
        r"[^a-z0-9-]",
        "-",
        document_name.lower()
    )
    bucket_name = f"{safe_document_name}-{document_id}"

    s3client.create_bucket(
        Bucket=bucket_name,
        CreateBucketConfiguration={
            "LocationConstraint": "eu-west-2"
        }
    )
    bucket = {
        "Name": bucket_name
    }

    key = f"documents/{document_id}/original.pdf"

    s3.upload_file(
        pdf_path,
        bucket,
        key,
        ExtraArgs={
            "ContentType": "application/pdf"
        }
    )

    return bucket, key

def parse_pdf_to_chunks(pdf_path: str, document_name: str, document_desc: str, special_types: list[str], db_connection, bucket_key, user_id: str):

    # Parse a PDF and store its text chunks in PostgreSQL.

    reader = PdfReader(pdf_path) # object that can read pdfs

    chunk_index = 0

    chunks = [["", []]]

    for page_number, page in enumerate(reader.pages, start=1):
        # this currently chunks by page which is not the best strategy long term

        text = page.extract_text()

        if not text:
            continue

        # Placeholder chunking strategy for now.
        # This can later be replaced by a proper chunker.
        chunks[0][0] += text + "\n"
        chunks[0][1].append(page_number)

    for i in chunks:
        chunk, chunk_pages = i
        data_handlers.add_chunk(db_connection, document_name, document_desc, chunk_pages, chunk_index, bucket_key, chunk, user_id)
        find_relevances(db_connection, chunk, document_desc, document_name, chunk_index, special_types, user_id)
        chunk_index += 1

def find_relevances(client, text, text_description, document_name, chunk_no, special_types, user_id):

    # algorithmically idenitfies tasks a chunk may be associated wiht / useful for 
    # and adds that relevancy to the supabase database

    relevances = []
    if "utility_bill" in special_types:
        task_name = "scope2_from_utility_bills"
        relevances.append(task_name)
        data_handlers.add_relevancy_to_chunk(client, document_name, chunk_no, task_name, user_id)
    # etc etc

def main_orchestrator(pdf_path, document_name, description, special_types, user_id):

    document_id = str(uuid.uuid4()) # may be different to the supabase uuid

    # to be implemented later:
    # bucket, bucket_key = archive_pdf(pdf_path, document_id, document_name, description, special_types, bucket)
    bucket_key = "" # placeholder

    # connect to database get db_connection
    sb_url = os.getenv("SUPABASE_URL")
    sb_key = os.getenv("SUPABASE_ADMIN_KEY")

    db_connection = create_client(
        sb_url,
        sb_key
    )

    parse_pdf_to_chunks(pdf_path, document_name, description, special_types, db_connection, bucket_key, user_id)


@router.post("/documents")
async def upload_document(
    background_tasks: BackgroundTasks,
    document_name: str = Form(...),
    description: str = Form(...), 
    file: UploadFile = File(...),
    special_types: List[str] = Form([]),
    user_id: str = Depends(user_verifier.get_current_user)
    ):

    print("PARSER REACHED")

    # FastAPI application functions

    cache_path = os.getenv("CACHE_PATH")

    # tested and works
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False, dir=cache_path) as tmp:
            
        file_path = tmp.name

        contents = await file.read()
        tmp.write(contents)

        document_name =  f"{document_name}_{os.path.basename(file_path)}"

        print("FILE UPLOADED")

    await run_in_threadpool(main_orchestrator, file_path, document_name, description, special_types, user_id)

    print({"status": "success", "document_name": document_name, "file_path": file_path})

    #background_tasks.add_task(os.remove, file_path)

    return {"status": "success", "document_name": document_name, "file_path": file_path}


